kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/kir-dev/k8s
        revision: HEAD
        directories:
          - path: "*"
#          - path: startsch
#            exclude: true
          # - path: argocd
          #   exclude: true
          # - path: application-set
          #   exclude: true
          # - path: tempo
          #   exclude: true
          # - path: opentelemetry-collector
          #   exclude: true
          # - path: loki
          #   exclude: true
          # - path: kube-prometheus-stack
          #   exclude: true
          # - path: cnpg
          #   exclude: true
          # - path: cert-manager
          #   exclude: true
  template:
    metadata:
      name: "{{.path.basename}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/kir-dev/k8s
        path: "{{.path.path}}"
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
