# https://artifacthub.io/packages/helm/grafana/tempo
# https://github.com/grafana/helm-charts/tree/main/charts/tempo

namespace: monitoring
helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    version: 1.24.3
    releaseName: tempo
    namespace: monitoring
    includeCRDs: true
    valuesInline:
      tempo:
        repository: grafana/tempo
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
            ephemeral-storage: 300Mi
          requests:
            cpu: .1
            memory: 150Mi
            ephemeral-storage: 50Mi
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
